name: Update Fuel Prices

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  schedule:
  # Runs every Thursday at 7AM Malaysia Time (23:00 UTC Wednesday)
    - cron: "0 23 * * Wed"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python scripts/update.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add price.json
          git commit -m "Updated fuel prices" || echo "No changes to commit"
          git push

      - name: Notify Discord
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          RON95=$(jq -r '.RON95.Price' price.json)
          RON97=$(jq -r '.RON97.Price' price.json)
          DIESEL=$(jq -r '.Diesel.Price' price.json)
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"content\": \"Latest Fuel Prices:\\nPETRONAS Primax 95 with Pro-Drive: RM$RON95\\nPETRONAS Primax 97 with Pro-Race: RM$RON97\\nPETRONAS Dynamic Diesel Euro 5 with Pro-Drive: RM$DIESEL\"}" \
               $DISCORD_WEBHOOK_URL
